### ISSUE TITLE
최종 데모 버그

### ISSUE THREAD

**Issue by yoonminsang** [woowa-techcamp-2021/deal-13#104]
- [x] db 조인버그
- [x] pm2로 json파일 못불러오는 버그(express type module이라서.. 정확히는 시간이 없어서)
- [x] pushstate 메뉴에서 이상해지는 오류
- [x] 새로고침이 안되는 페이지 존재하는 버그
- [x] express에서 바로 sendfile이 안되서 ejs 설치한 것

**Comment by kowoohyuk** [comment]
늦게나마 수정했습니다...  
이제 채팅방이 정상으로 나옵니다 ㅠㅠ
